name: Download Artifacts

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download artifacts
        shell: pwsh
        run: |
          $access_token="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"
          $headers = @{
              "Authorization" = "token $access_token"
              "Accept" = "application/vnd.github+json"
              "X-GitHub-Api-Version" = "2022-11-28"
            }
            
          $artifactsUrl = "https://api.github.com/repos/Saujol/Python-Sample-Application/actions/artifacts/797157236/zip"
          Invoke-WebRequest -Uri $artifactsUrl -Headers $headers -OutFile "/home/dropArtifacts.zip"
      
      - name: List files
        run: |
          ls /home/
