name: Download Artifacts

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download artifacts
        shell: pwsh
        run: |
          cd /home/
          sudo curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Saujol/Python-Sample-Application/actions/artifacts/797215217/zip
      
      - name: List files
        run: |
          ls /home/
